[project]
name = "the-distributor"
version = "0.1.0"
description = ""
authors = [
    {name = "Garrett Anderson",email = "g@devnull.rip"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "the_distributor", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
